# Generated by django 2.0.4 on 2019-04-17 06:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0002_bookmark_widget'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Widget',
            new_name='UserComponent',
        ),
        migrations.RenameModel(
            old_name='SystemSettings',
            new_name='UserSetting',
        ),
    ]
