# Generated by django 2.0.4 on 2019-05-15 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0003_auto_20190417_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Title')),
                ('url_name', models.CharField(max_length=64, verbose_name='Url Name')),
                ('query', models.CharField(blank=True, max_length=1000, verbose_name='Query String')),
                ('is_share', models.BooleanField(default=False, verbose_name='Is Shared')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': '视图',
                'verbose_name_plural': '视图',
            },
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='usercomponent',
            options={'verbose_name': '组件', 'verbose_name_plural': '组件'},
        ),
        migrations.AlterModelOptions(
            name='usersetting',
            options={'verbose_name': '设置', 'verbose_name_plural': '设置'},
        ),
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
